version: '3'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
