services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=app

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/var/www
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=app
    tty: true

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"

  node:
    image: node:22-alpine
    volumes:
      - ./:/var/www
    ports:
      - "3000:3000"
    working_dir: /var/www
    tty: true

  mailer:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "8081:8025"

volumes:
  mysql:
