; Maximum amount of memory a script may consume
; https://php.net/memory-limit
memory_limit = 256M

; Maximum allowed size for uploaded files.
upload_max_filesize = 20M

; Must be greater than or equal to upload_max_filesize
post_max_size = 20M
